#!/bin/bash
echo "🚀 Launching Stable Simulation (No robot_perception)"
echo "===================================================="
echo ""
echo "🔧 Building packages..."
colcon build --packages-select robot_gazebo robot_description robot_control --symlink-install
echo ""
echo "🔄 Sourcing setup..."
source install/setup.bash
echo ""
echo "🎯 Launching simulation..."
echo "Features included:"
echo "  ✅ Gazebo with robot"
echo "  ✅ Camera sensor"
echo "  ✅ LiDAR sensor"
echo "  ✅ SLAM mapping"
echo "  ✅ RViz visualization"
echo "  ✅ Teleop control"
echo "  ❌ robot_perception (disabled to prevent crashes)"
echo ""
echo "🎮 Controls (in teleop terminal):"
echo "  i = forward"
echo "  j = turn left"
echo "  l = turn right"
echo "  k = stop"
echo "  , = backward"
echo ""
echo "🚀 Starting simulation..."
ros2 launch robot_gazebo complete_simulation.launch.py