controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Controller Manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

# Differential Drive Controller Configuration
diff_drive_controller:
  ros__parameters:
    # Wheel joints
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    
    # Kinematics
    wheel_separation: 0.26  # Distance between wheels
    wheel_radius: 0.0325   # Wheel radius
    
    # Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Publishing
    publish_rate: 50.0
    publish_odom: true
    publish_odom_tf: true
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
        
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 2.0
        min_velocity: -2.0
        max_acceleration: 1.5
        min_acceleration: -1.5

# Hardware Interface Configuration
hardware_interface:
  ros__parameters:
    hardware_plugin: gazebo_ros2_control/GazeboSystem

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint