# SLAM Toolbox Configuration for Dojo Robot Simulation

slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint  # Changed from base_link to base_footprint for better navigation
    scan_topic: /scan
    use_map_saver: true
    mode: mapping  # localization, mapping, lifelong
    
    # Solver Parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # ROS Parameters
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02  # 50 Hz
    map_update_interval: 2.0  # More frequent updates
    resolution: 0.05
    max_laser_range: 12.0  # Match your LiDAR range
    minimum_time_interval: 0.2  # Reduced from 0.5 for more responsive updates
    transform_timeout: 0.1  # Reduced timeout for faster recovery
    tf_buffer_duration: 10.0  # Reduced buffer duration
    stack_size_to_use: 40000000  # 40MB
    enable_interactive_mode: true
    
    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1  # Reduced for more frequent updates
    minimum_travel_heading: 0.2   # Reduced for more frequent updates
    scan_buffer_size: 30  # Increased buffer size
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.08  # Reduced for better matching
    link_scan_maximum_distance: 2.0  # Increased search distance
    loop_search_maximum_distance: 5.0  # Increased loop closure search
    do_loop_closing: true 
    loop_match_minimum_chain_size: 5  # Reduced for faster loop closure         
    loop_match_maximum_variance_coarse: 3.5  # Increased variance threshold  
    loop_match_minimum_response_coarse: 0.25  # Reduced threshold    
    loop_match_minimum_response_fine: 0.35  # Reduced threshold
    
    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 
    
    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true