<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- RPLIDAR A1M8 Parameters -->
  <xacro:property name="lidar_radius" value="0.038" />  <!-- Approximate radius of the LiDAR -->
  <xacro:property name="lidar_height" value="0.045" />   <!-- Approximate height of the LiDAR -->

  <!-- RPLIDAR A1M8 Link -->
  <link name="rplidar_link">
    <visual>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="sensor_white"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${lidar_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- The joint is already defined in dojo_robot.urdf.xacro -->
</robot>
