/**:
  ros__parameters:
    use_sim_time: False
    
    # Common costmap parameters
    robot_radius: 0.22
    resolution: 0.05
    track_unknown_space: true
    lethal_cost_threshold: 253
    unknown_cost_value: 255
    trinary_costmap: true
    transform_tolerance: 0.2
    map_update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    static_map: true
    rolling_window: false
    width: 10
    height: 10
    origin_x: -5.0
    origin_y: -5.0
    
    # Inflation parameters
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    
    # Obstacle layer
    obstacle_layer:
      enabled: true
      obstacle_range: 2.5
      raytrace_range: 3.0
      inflation_radius: 0.55
      track_unknown_space: true
      
    # Static layer  
    static_layer:
      enabled: true
      
    # Inflation layer
    inflation_layer:
      enabled: true
      cost_scaling_factor: 10.0
      inflation_radius: 0.55
