/**:
  ros__parameters:
    use_sim_time: False
    autostart: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    global_frame: map
    robot_base_frame: base_link
    robot_radius: 0.22
    transform_tolerance: 0.2
    
    # Planner Server
    planner_server:
      ros__parameters:
        expected_planner_frequency: 20.0
        planner_plugins: ["GridBased"]
        GridBased:
          plugin: "nav2_navfn_planner/NavfnPlanner"
          tolerance: 0.5
          use_astar: false
          allow_unknown: true
    
    # Controller Server  
    controller_server:
      ros__parameters:
        controller_frequency: 20.0
        min_x_velocity_threshold: 0.001
        min_y_velocity_threshold: 0.5
        min_theta_velocity_threshold: 0.001
        failure_tolerance: 0.3
        progress_checker_plugin: "progress_checker"
        goal_checker_plugins: ["general_goal_checker", "precise_goal_checker"]
        controller_plugins: ["FollowPath"]
        
        # FollowPath Controller
        FollowPath:
          plugin: "dwb_core::DWBLocalPlanner"
          debug_trajectory_details: True
          min_vel_x: 0.0
          min_vel_y: 0.0
          max_vel_x: 0.26
          max_vel_y: 0.0
          max_vel_theta: 1.0
          min_speed_xy: 0.0
          max_speed_xy: 0.26
          min_speed_theta: 0.0
          acc_lim_x: 2.5
          acc_lim_y: 0.0
          acc_lim_theta: 3.2
          decel_lim_x: -2.5
          decel_lim_y: 0.0
          decel_lim_theta: -3.2
          vx_samples: 20
          vy_samples: 5
          vtheta_samples: 20
          sim_time: 1.7
          linear_granularity: 0.025
          angular_granularity: 0.025
          transform_tolerance: 0.2
          xy_goal_tolerance: 0.25
          trans_stopped_velocity: 0.25
          short_circuit_trajectory_evaluation: True
          stateful: True
          critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
          BaseObstacle.scale: 0.02
          PathAlign.scale: 0.5
          PathAlign.forward_point_distance: 0.1
          GoalAlign.scale: 0.5
          GoalAlign.forward_point_distance: 0.1
          PathDist.scale: 0.5
          GoalDist.scale: 0.5
          RotateToGoal.scale: 32.0
          RotateToGoal.slowing_factor: 5.0
          RotateToGoal.lookahead_time: -1.0
          
        # Progress Checker
        progress_checker:
          plugin: "nav2_controller::SimpleProgressChecker"
          required_movement_radius: 0.5
          movement_time_allowance: 10.0
          
        # Goal Checkers
        general_goal_checker:
          plugin: "nav2_controller::SimpleGoalChecker"
          xy_goal_tolerance: 0.25
          yaw_goal_tolerance: 0.25
          
        precise_goal_checker:
          plugin: "nav2_controller::SimpleGoalChecker"
          xy_goal_tolerance: 0.1
          yaw_goal_tolerance: 0.1
