controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    # Controller Manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
    # Controller Manager Parameters
    robot_description: robot_description
    robot_description_semantic: ''
    robot_description_planning: ''
    robot_description_kinematics: ''
    robot_description_joint_limits: ''
    robot_description_planning_joint_limits: ''
    robot_description_planning_cartesian_limits: ''
    robot_description_kinematics_cache: ''

# Differential Drive Controller Configuration
diff_drive_controller:
  ros__parameters:
    # Wheel joints
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    
    # Kinematics
    wheel_separation: 0.26  # Distance between wheels
    wheel_radius: 0.0325   # Wheel radius
    
    # Command timeout (seconds)
    cmd_vel_timeout: 0.25
    
    # Enable/disable odometry and TF publishing
    enable_odom_tf: true
    
    # Open loop control (set to false for better accuracy with wheel encoders)
    open_loop: true
    
    # Wheel separation multiplier (tune if needed)
    wheel_separation_multiplier: 1.0
    
    # Wheel radius multiplier (tune if needed)
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    # Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Publishing
    publish_rate: 50.0
    publish_odom: true
    publish_odom_tf: true
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 0.5
        min_velocity: -0.5
        max_acceleration: 0.5
        min_acceleration: -0.5
        
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
    
    # PID parameters for wheel velocity control
    wheel_joints:
      front_left_wheel_joint: {p: 0.1, i: 0.0, d: 0.0}
      front_right_wheel_joint: {p: 0.1, i: 0.0, d: 0.0}
      rear_left_wheel_joint: {p: 0.1, i: 0.0, d: 0.0}
      rear_right_wheel_joint: {p: 0.1, i: 0.0, d: 0.0}

# Hardware Interface Configuration
hardware_interface:
  ros__parameters:
    hardware_plugin: gazebo_ros2_control/GazeboSystem
    control_period: 0.01  # 100 Hz update rate
    use_sim_time: true
    
    # Gazebo specific parameters
    gazebo:
      robot_param: robot_description
      robot_sim_type: gazebo_ros2_control/GazeboSystem
      
      # Control mode (position, velocity, or effort)
      control_mode: velocity
      
      # Maximum effort for wheel joints
      max_effort: 0.1

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint